---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: frontend           # Name of the Kubernetes resource
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: frontend        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: frontend
        app.kubernetes.io/name: frontend
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: frontend
        image: frontend
        env:
          - name: DB_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: paaks-secret
                key: dbConnStr
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: paaks-secret
                key: secretKey
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000  # Should match the port number that the Go application listens on
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
