---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: db-mgr           # Name of the Kubernetes resource
  labels:
    app.kubernetes.io/name: db-mgr
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: db-mgr        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: db-mgr
        app.kubernetes.io/name: db-mgr
    spec:                        # Spec for the container which will run in the Pod
      terminationGracePeriodSeconds: 5
      containers:
      - name: db-mgr
        image: db-mgr
        env:
          - name: DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: paaks-secret
                key: dbConnStr
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: paaks-secret
                key: secretKey
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2000  # Should match the port number that the Go application listens on
        volumeMounts:
        - name: blockdisk01
          mountPath: /tmp/storage
      volumes:
      - name: blockdisk01
        persistentVolumeClaim:
          claimName: pv-main-fs
---
apiVersion: v1
kind: Service
metadata:
  name: db-mgr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: db-mgr
  ports:
  - port: 80
    targetPort: 3000
