---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: admin           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: admin        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: admin 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: admin
        image: admin 
        env:
          - name: DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: paaks-secret
                key: dbConnStr
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: paaks-secret
                key: secretKey
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000  # Should match the port number that the Go application listens on
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /health_check
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
  - port: 80
    targetPort: 3000
