---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: filesystem           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: filesystem        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: filesystem 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: filesystem
        image: filesystem
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: paaks-secret
                key: secretKey
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000  # Should match the port number that the Go application listens on
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /health_check
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: blockdisk01
          mountPath: /tmp/storage
      volumes:
      - name: blockdisk01
        persistentVolumeClaim:
          claimName: pv-main-fs
---
apiVersion: v1
kind: Service
metadata:
  name: filesystem
spec:
  type: ClusterIP
  selector:
    app: filesystem
  ports:
  - port: 80
    targetPort: 3000
